### sin imagenes
GET http://localhost:1337/api/propiedades

### ahora con imagenes (agruegás ?populate=* a la ruta)
GET http://localhost:1337/api/propiedades?populate=*

### Ahora pido categorías como me dice desde localhost:1337
GET http://localhost:1337/api/categorias

### Ahora pido categorías como se explica en https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/rest/populating-fields.html#relation-media-fields
### Retorna lo mismo que GET http://localhost:1337/api/propiedades
GET http://localhost:1337/api/propiedades?populate[0]=categorias